### ISSUE TITLE
Add links to dependancies

### ISSUE THREAD

**Issue by AntumArk** [avandalen/avdweb_AnalogReadFast#2]
Can you please add links to 
#include <Streaming.h>
#include <StopWatch.h>
#include <Albert.h>
?

**Comment by avandalen** [comment]
see here:
https://www.avdweb.nl/arduino/misc/troubleshooting

From: Zinc 
Sent: Friday, October 4, 2019 12:13 PM
To: avandalen/avdweb_AnalogReadFast 
Cc: Subscribed 
Subject: [avandalen/avdweb_AnalogReadFast] Add links to dependancies (#2)

Can you please add links to
#include <Streaming.h>
#include <StopWatch.h>
#include <Albert.h>
?
