### ISSUE TITLE
License mismatch between LICENSE.md and code header

### ISSUE THREAD

**Issue by nomakewan** [avandalen/avdweb_AnalogReadFast#7]
According to the LICENSE.md file on this repository, this code is licensed under an MIT License. According to the header of `avdweb_AnalogReadFast.h` however, this code is licensed under the GPL v3 license.

This conflict should be resolved as these two licenses are very different from one another. Thank you!

**Comment by avandalen** [comment]
I have deleted the licence in the header, so it should be ok now
